
 
import os
import sys
 
token = os.environ.get("HF_TOKEN", "").strip()
 
if not token:
    print("ERROR: HF_TOKEN không có trong environment!")
    print("  GitHub Actions: thêm vào repo Secrets")
    print("  Local build:    export HF_TOKEN=hf_xxx trước khi chạy")
    sys.exit(1)
 
# Ghi token vào file tạm — sẽ bị bundle vào exe
output = f'''# AUTO-GENERATED — DO NOT COMMIT
# Generated by build_config.py during CI build
BUNDLED_HF_TOKEN = "{token}"
'''
 
with open("core/_bundled_token.py", "w") as f:
    f.write(output)
 
print(f"[BUILD] Token injected: hf_...{token[-4:]}")
 